### PR TITLE
GPIB-645

### PR DESCRIPTION
**Pull request by rodonguyen**
- [Link to ticket](https://dltx.atlassian.net/jira/software/projects/GPIB/boards/6?selectedIssue=GPIB-645)
- On User Portal, address type is always `non-custodial` when adding a new address
- Code: use onClick to re-render the new selection. Logic is correct at the beginning.

### CODE REVIEW

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Need to resolve conflicts

**Comment by rodonguyen** [comment]
(deleted screenshot)

**Comment by bitcoinbrisbane** [comment]
I think this is a screenshot for #156

**Comment by rodonguyen** [comment]
Yeah, you are right. Let me delete that.

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Looks good, however, lets rename the branch correctly :)

**Review by bitcoinbrisbane — APPROVED** [review]

**Pull request merged**
