### PR TITLE
GPIB-623

### PR DESCRIPTION
**Pull request by rodonguyen**
- [Link to ticket](https://dltx.atlassian.net/jira/software/projects/GPIB/boards/6?selectedIssue=GPIB-623)
- Covert checkbox to togglebutton -> more consistent 
- Code: 
  - Read Formik Docs to know how to send value with Formik Form! 
  - Create a new `ToggleButton.js` file for this ticket as I'm having issue with CSS styling when using existing `Toggle.js`

### CODE REVIEW

**Comment by bitcoinbrisbane** [comment]
image

Seem to be smaller than the others

image

**Comment by bitcoinbrisbane** [comment]
> * [Link to ticket](https://dltx.atlassian.net/jira/software/projects/GPIB/boards/6?selectedIssue=GPIB-623)
> * Covert checkbox to togglebutton -> more consistent
> * Code:
>   
>   * Read Formik Docs to know how to send value with Formik Form!
>   * Create a new `ToggleButton.js` file for this ticket as I'm having issue with CSS styling when using existing `Toggle.js`

Lets add screenshots too :)

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Lets play with the style.  Not sure why we need custom style

* Blue backgournd seems different
* Toggles look smaller

**Comment by rodonguyen** [comment]
Updated Size and Colors:
- Use the same size with Toggle.js
- Still has to use a **custom** ToggleButton.js as they both use the onClick in different ways. @bitcoinbrisbane: Let me know if you want me to work on merging 2 current Toggle Button files into 1.
- Get color vars from `constants/` => colors are consistent now.

image

**Review by bitcoinbrisbane — APPROVED** [review]

**Pull request merged**
